/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Providers:

var REG_NONE = NewRegistrar("none_primary");
var DNS_CLOUDFLAREAPI = NewDnsProvider("cloudflareapi_primary");

// Domains:

D("chitzu.ro", REG_NONE, DnsProvider(DNS_CLOUDFLAREAPI),
    DefaultTTL(3600),
    A("@", "158.180.26.241"),
    MX("@", 10, "mx01.mail.icloud.com."),
    MX("@", 10, "mx02.mail.icloud.com."),
    TXT("@", "apple-domain=X5vJJXLOiogqLqR1"),
    TXT("@", "v=spf1 mx a:mail.chitzu.ro include:icloud.com ~all"),
    TXT("_dmarc", "v=DMARC1; p=reject; rua=mailto:dmarc@chitzu.ro; fo=1", TTL(1)),
    TXT("mail._domainkey", "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh8Y/U03AYdCDEOkfHWPYqrH6a/JG9vhOGGFjHGTyIJaPW8lg10URpYdSJs2tVSBP4B/d/tNDocjTJMRABgKksk5OmVBFWSxg3RrV8GRTFkkrl3wMARXGT4LQy7n7K401S+qAYhZvPSww1S9cEmwO5EzNGcycJLEetCze2IqLDBrxjqmr57p8kmaFhdETo5H7BuKc2GYUE89YC26f2oz4MV85p9vLQZoXko2i3BdFHHRbFuB+6vbiDzjNLTHsatSww6UqxC6zUNr7y0eAy/x/1ZPGwiT2kQvnjSqSkcq+l8o0iB0AkqEDes6LAlEDY3C+tV3Jptkk2gmbAjZ5SW6VdwIDAQAB", TTL(1)),
    CNAME("sig1._domainkey", "sig1.dkim.chitzu.ro.at.icloudmailadmin.com."),
    SRV("_minecraft._tcp", 10, 100, 25565, "chitzu.ro.", TTL(300)),
    A("analytics", "158.180.26.241", TTL(1)),
    A("chat", "158.180.26.241", TTL(1)),
    CNAME("home", "nirod.go.ro.", TTL(1)),
    CNAME("*.home", "nirod.go.ro.", TTL(1)),
    A("navidrome", "158.180.26.241", TTL(1)),
);

